retry domain joined if failed and add healthcheck

diff --git a/playbooks/roles/cyclecloud_pbs/cluster-init/scripts/3-joindomain.sh.j2 b/playbooks/roles/cyclecloud_pbs/cluster-init/scripts/3-joindomain.sh.j2
--- a/playbooks/roles/cyclecloud_pbs/cluster-init/scripts/3-joindomain.sh.j2
+++ b/playbooks/roles/cyclecloud_pbs/cluster-init/scripts/3-joindomain.sh.j2
@@ -29,12 +29,26 @@ ADMIN_DOMAIN={{ ad_join_domain }}
 ADMIN_NAME={{ ad_join_user }}
 ADMIN_PASSWORD={{ cc_password }}
 
-echo $ADMIN_PASSWORD| realm join -U $ADMIN_NAME $ADMIN_DOMAIN  
+delay=15
+n=1
+max_retry=3
 
-if [ ! -f "/etc/sssd/sssd.conf" ]; then
-  echo "Failed to domain join the server"
-  exit 1
-fi
+while true; do
+  echo $ADMIN_PASSWORD| realm join -U $ADMIN_NAME $ADMIN_DOMAIN  
+
+  if [ ! -f "/etc/sssd/sssd.conf" ]; then
+    if [[ $n -le $max_retry ]]; then
+      echo "Failed to domain join the server -  Attempt $n/$max_retry:"
+      sleep $delay
+      ((n++))
+    else
+      echo "Failed to domain join the server after $n attempts."
+      exit 1
+    fi
+  else
+    break
+  fi
+done
 
 sed -i 's@use_fully_qualified_names.*@use_fully_qualified_names = False@' /etc/sssd/sssd.conf
 sed -i 's@ldap_id_mapping.*@ldap_id_mapping = False@' /etc/sssd/sssd.conf
@@ -44,20 +58,27 @@ ipaddr=$(hostname -i)
 system_hostname=$(hostname)
 target_hostname="ip-$(printf '%02X' ${ipaddr//./ })"
 if [ "$system_hostname" != "$target_hostname" ]; then
-	logger -s "Warning: incorrect hostname ($system_hostname), it should be $target_hostname, updating"
-	hostname $target_hostname
+  logger -s "Warning: incorrect hostname ($system_hostname), it should be $target_hostname, updating"
+  hostname $target_hostname
 fi
 etc_hostname=$(</etc/hostname)
 if [ "$etc_hostname" != "$target_hostname" ]; then
-	logger -s "Warning: incorrect /etc/hostname ($etc_hostname), it should be $target_hostname, updating"
-	echo $target_hostname > /etc/hostname
+  logger -s "Warning: incorrect /etc/hostname ($etc_hostname), it should be $target_hostname, updating"
+  echo $target_hostname > /etc/hostname
 fi
 eth0_hostname=$(grep DHCP_HOSTNAME /etc/sysconfig/network-scripts/ifcfg-eth0 | cut -d'=' -f2)
 if [ "$eth0_hostname" != "$target_hostname" ]; then
-	logger -s "Warning: incorrect DHCP_HOSTNAME in /etc/sysconfig/network-scripts/ifcfg-eth0 ($etc_hostname), it should be $target_hostname, updating"
-	sed -i "s/^DHCP_HOSTNAME=.*\$/DHCP_HOSTNAME=$target_hostname/g" /etc/sysconfig/network-scripts/ifcfg-eth0
+  logger -s "Warning: incorrect DHCP_HOSTNAME in /etc/sysconfig/network-scripts/ifcfg-eth0 ($etc_hostname), it should be $target_hostname, updating"
+  sed -i "s/^DHCP_HOSTNAME=.*\$/DHCP_HOSTNAME=$target_hostname/g" /etc/sysconfig/network-scripts/ifcfg-eth0
 fi
 
 systemctl restart NetworkManager
 systemctl restart sssd
 systemctl restart sshd
+
+# Check if we are domain joined
+realm list | grep active-directory
+if [ $? -eq 1 ]; then
+  echo "Node $(hostname) is not domain joined"
+  exit 1
+fi
