exit 1 in case of mount error. improved messages

diff --git a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2 b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
--- a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
+++ b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
@@ -9,23 +9,31 @@ modinfo lustre >&/dev/null || exit 0
 max_retry=5
 delay=5
 
+# Check if the lustre kernel modules can be loaded
 attempt=1
 while true; do
     if modprobe lustre; then
         break
     else
         if (( attempt <= max_retry )) ; then
-            echo "Unable to mount lustre. Retry $attempt of $max_retry ..."
+            echo "Unable to load lustre kernel module. Retry $attempt of $max_retry ..."
             (( attempt++ ))
             sleep $delay
         else
-            echo "Unable to mount lustre. Exiting..."
-            exit 0
+            echo "Unable to load lustre kernel module. Exiting..."
+            exit 1
         fi
     fi
 done
 
+# Mount the lustre filesystem
 mkdir $lustre_mount
 echo "${lustre_vm}@tcp0:/LustreFS $lustre_mount lustre flock,defaults,_netdev 0 0" >> /etc/fstab
-mount -a
+mount $lustre_mount 
+if [ $? -eq 1 ]; then
+  echo "Unable to mount lustre"
+  exit 1
+fi
+
+# TODO : don't chmod 777, but instead reorganize lustre directories structure and permissions
 chmod 777 $lustre_mount
