retry 'modprobe lustre' and fail on error (client)

diff --git a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2 b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
--- a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
+++ b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
@@ -3,10 +3,20 @@
 lustre_vm=lustre
 lustre_mount=/lustre
 
-if ! modprobe lustre; then
-    echo "Unable to mount lustre"
-    # silently fail here
-    exit 0
+success=0
+for retry in {1..10} ; do
+    if ! modprobe lustre; then
+        echo "Unable to mount lustre. Retrying..."
+        sleep 5
+    else
+        success=1
+        break
+    fi
+done
+
+if [ $success -eq 0 ]; then
+    echo "ERROR Unable to mount lustre"
+    exit 1
 fi
 
 mkdir $lustre_mount
