first round of PTR records for reverse DNS

diff --git a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2 b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
--- a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
+++ b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
@@ -21,25 +21,28 @@ delay=15
 n=1
 max_retry=3
 
-while true; do
-  current_hostname=$(hostname)
-  target_hostname=$(jetpack config cyclecloud.node.name)
+standalone_dns=$(jetpack config cyclecloud.hosts.standalone_dns.enabled | tr '[:upper:]' '[:lower:]')
+if [[ $standalone_dns != "true" ]]; then
+  while true; do
+    current_hostname=$(hostname)
+    target_hostname=$(jetpack config cyclecloud.node.name)
 
-  if [[ $n -le $max_retry ]]; then
-    if [ "$current_hostname" != "$target_hostname" ]; then
-      logger -s "hostname not renamed -  Attempt $n/$max_retry:"
-      enforce_hostname $current_hostname $target_hostname
-      sleep $delay
+    if [[ $n -le $max_retry ]]; then
+      if [ "$current_hostname" != "$target_hostname" ]; then
+        logger -s "hostname not renamed -  Attempt $n/$max_retry:"
+        enforce_hostname $current_hostname $target_hostname
+        sleep $delay
+      else
+        logger -s "hostname successfully renamed"
+        break
+      fi
+      ((n++))
     else
-      logger -s "hostname successfully renamed"
-      break
+      logger -s "Failed to rename host after $n attempts."
+      exit 1
     fi
-    ((n++))
-  else
-    logger -s "Failed to rename host after $n attempts."
-    exit 1
-  fi
-done
+  done
+fi
 
 n=1
 max_retry=3
