rename node before domain join

diff --git a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2 b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
--- a/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
+++ b/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
@@ -36,6 +36,29 @@ n=1
 max_retry=3
 
 while true; do
+  current_hostname=$(hostname)
+  target_hostname=$(jetpack config cyclecloud.node.name)
+
+  if [[ $n -le $max_retry ]]; then
+    if [ "$current_hostname" != "$target_hostname" ]; then
+      logger -s "hostname not renamed -  Attempt $n/$max_retry:"
+      enforce_hostname $current_hostname $target_hostname
+      sleep $delay
+    else
+      logger -s "hostname successfully renamed"
+      break
+    fi
+    ((n++))
+  else
+    logger -s "Failed to rename host after $n attempts."
+    exit 1
+  fi
+done
+
+n=1
+max_retry=3
+
+while true; do
   logger -s "Domain join on $ADMIN_DOMAIN"
   echo $ADMIN_PASSWORD| realm join -U $ADMIN_NAME $ADMIN_DOMAIN
 
@@ -62,27 +85,6 @@ echo "ad_gpo_access_control = disabled" >> /etc/sssd/sssd.conf
 
 systemctl restart sssd
 systemctl restart sshd
-
-n=1
-while true; do
-  current_hostname=$(hostname)
-  target_hostname=$(jetpack config cyclecloud.node.name)
-
-  if [[ $n -le $max_retry ]]; then
-    if [ "$current_hostname" != "$target_hostname" ]; then
-      logger -s "hostname not renamed -  Attempt $n/$max_retry:"
-      enforce_hostname $current_hostname $target_hostname
-      sleep $delay
-    else
-      logger -s "hostname successfully renamed"
-      break
-    fi
-    ((n++))
-  else
-    logger -s "Failed to rename host after $n attempts."
-    exit 1
-  fi
-done
 
 # Check if we are domain joined
 realm list | grep active-directory
