remote viz cluster

diff --git a/playbooks/cccluster.yml b/playbooks/cccluster.yml
--- a/playbooks/cccluster.yml
+++ b/playbooks/cccluster.yml
@@ -12,6 +12,7 @@
   vars:
     - ansible_python_interpreter: /usr/bin/python3
     - lookup_img_file: image_lookup.yml
+    - remoteviz_lookup_img_file: remoteviz_image_lookup.yml
   vars_files:
     - '{{global_config_file}}'
 
@@ -32,6 +33,16 @@
   - name: Init image lookup file
     shell: |
         echo "image_lookup:" > {{lookup_img_file}}
+    args:
+      executable: /bin/bash
+      warn: false
+    delegate_to: localhost
+    connection: local
+    become: false
+
+  - name: Init remoteviz image lookup file
+    shell: |
+        echo "image_lookup:" > {{remoteviz_lookup_img_file}}
     args:
       executable: /bin/bash
       warn: false
@@ -67,6 +78,34 @@
     include_vars:
       file: '{{lookup_img_file}}'
 
+# Rewrite remoteviz.image propertie to include the image version number for images stored in the SIG
+  - name: Overwrite image version when needed
+    shell: |
+      # If image name end with /latest, then retrieve the image version from the SIG
+      image={{item.image}}
+      version=${image##*/}
+      if [ "$version" == "latest" ]; then
+        img_def=${image%/*}
+        img_name=${img_def##*/}
+        img_id=$(az sig image-version list -g {{ resource_group }} -r {{ sig_name }} -i $img_name --query "[].id" -o tsv | sort | tail -n 1)
+        if [ "$img_id" == "" ]; then
+          echo "unable to retrieve image id for $img_name"
+          exit 1
+        else
+          echo "  {{item.name}}: $img_id" >> {{remoteviz_lookup_img_file}}
+        fi
+      fi
+    args:
+      executable: /bin/bash
+    delegate_to: localhost
+    connection: local
+    become: false
+    with_items: "{{remoteviz}}"
+
+  - name: Load lookup image version
+    include_vars:
+      file: '{{remoteviz_lookup_img_file}}'
+
   - include_role: 
       name: cyclecloud_cluster
       apply: 
@@ -77,6 +116,7 @@
       cc_admin_user: '{{admin_user}}'
       cc_password: '{{password.stdout}}'
       cc_queues: '{{queues}}'
+      cc_remoteviz: '{{remoteviz}}'
       cc_image_lookup: '{{image_lookup}}'
       cc_domain: '{{ad_join_domain}}'
       cc_ad_server: '{{ad_dns}}'
