suppress exit on erro in the last step

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -71,8 +71,9 @@ jobs:
           terraform destroy -auto-approve -parallelism=30 -var location=westeurope -var resource_group=$RESOURCE_GROUP ./tf
 
           # Return on error if any tasks failed
-          if [ "steps.configure.outcome" != "success" ]; then
-            echo "::error::Configure Step failed"
-            exit 1
-          fi
+          # TODO : Need to find a way to make tasks failed an this one to always run
+          #if [ "steps.configure.outcome" != "success" ]; then
+          #  echo "::error::Configure Step failed"
+          #  exit 1
+          #fi
 
