use vscode user and failed if config error

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -27,7 +27,7 @@ jobs:
 
     container:
       image: xpillons/hpcrover:2011.2317 
-      options: --user 0
+      options: --user vscode
 
     outputs:
         resource_group: ${{ steps.deployment.outputs.resource_group }}
@@ -62,4 +62,10 @@ jobs:
       - name: Remove Resources
         run: |
           terraform destroy -auto-approve -parallelism=30 -var location=westeurope -var resource_group=$RESOURCE_GROUP ./tf
+
+          # Return on error if any tasks failed
+          if [ "steps.deployment.outcome" != "success" ]; then
+            echo "::error::Configure Step failed"
+            exit 1
+          fi
 
